import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { fileURLToPath } from "node:url";

const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(scriptDir, "..");
const legalDir = path.join(root, "content", "legal");
const outFile = path.join(root, "src", "lib", "legal", "generated.ts");

function isMarkdownFile(fileName) {
    return fileName.toLowerCase().endsWith(".md");
}

function normalizeDate(value) {
    if (typeof value === "string") {
        return value;
    }

    if (value instanceof Date && !Number.isNaN(value.getTime())) {
        return value.toISOString().slice(0, 10);
    }

    return undefined;
}

function normalizeFrontMatter(data, slug) {
    const title = typeof data.title === "string" ? data.title : slug;
    const description =
        typeof data.description === "string" ? data.description : "";
    const updated = normalizeDate(data.updated);

    if (!description) {
        throw new Error(`Legal document '${slug}' missing description`);
    }

    return { title, description, updated };
}

function readDocuments() {
    if (!fs.existsSync(legalDir)) {
        return [];
    }

    const slugs = fs
        .readdirSync(legalDir)
        .filter(isMarkdownFile)
        .map((fileName) => fileName.replace(/\.md$/i, ""))
        .sort((a, b) => a.localeCompare(b));

    return slugs.map((slug) => {
        const fullPath = path.join(legalDir, `${slug}.md`);
        const raw = fs.readFileSync(fullPath, "utf8");
        const parsed = matter(raw);
        const frontMatter = normalizeFrontMatter(parsed.data ?? {}, slug);

        return {
            slug,
            ...frontMatter,
            content: String(parsed.content ?? "").trim(),
        };
    });
}

function toTsString(value) {
    return JSON.stringify(value);
}

function generate() {
    const documents = readDocuments();
    const bySlug = Object.fromEntries(documents.map((doc) => [doc.slug, doc]));

    const ts = `// This file is auto-generated by scripts/generate-legal.mjs
// Do not edit manually.

import type { LegalDocument } from "@/lib/legal/types";

export const legalDocumentsBySlug: Record<string, LegalDocument> = ${toTsString(bySlug)} as unknown as Record<string, LegalDocument>;
`;

    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, ts, "utf8");
}

generate();
