import fs from "node:fs";
import path from "node:path";
import matter from "gray-matter";
import { fileURLToPath } from "node:url";

// Resolve paths relative to this script so it works regardless of cwd.
const scriptDir = path.dirname(fileURLToPath(import.meta.url));
const root = path.resolve(scriptDir, "..");
const blogDir = path.join(root, "content", "blog");
const outFile = path.join(root, "src", "lib", "blog", "generated.ts");

function isMarkdownFile(fileName) {
    return fileName.toLowerCase().endsWith(".md");
}

function normalizeFrontMatter(data, slug) {
    const title = typeof data.title === "string" ? data.title : slug;
    const description =
        typeof data.description === "string" ? data.description : "";
    const date = typeof data.date === "string" ? data.date : "";
    const updated = typeof data.updated === "string" ? data.updated : undefined;
    const draft = typeof data.draft === "boolean" ? data.draft : false;
    const tags = Array.isArray(data.tags)
        ? data.tags.filter((t) => typeof t === "string")
        : undefined;

    if (!description) {
        throw new Error(`Blog post '${slug}' missing description`);
    }
    if (!date) {
        throw new Error(`Blog post '${slug}' missing date`);
    }

    return { title, description, date, updated, tags, draft };
}

function readPosts() {
    if (!fs.existsSync(blogDir)) {
        return [];
    }

    const slugs = fs
        .readdirSync(blogDir)
        .filter(isMarkdownFile)
        .map((f) => f.replace(/\.md$/i, ""));

    return slugs.map((slug) => {
        const fullPath = path.join(blogDir, `${slug}.md`);
        const raw = fs.readFileSync(fullPath, "utf8");
        const parsed = matter(raw);
        const fm = normalizeFrontMatter(parsed.data ?? {}, slug);
        return {
            slug,
            ...fm,
            content: String(parsed.content ?? "").trim(),
        };
    });
}

function stableSortDescByDate(posts) {
    return [...posts].sort((a, b) => {
        const ad = new Date(a.date).getTime();
        const bd = new Date(b.date).getTime();
        return bd - ad;
    });
}

function toTsString(value) {
    return JSON.stringify(value);
}

function generate() {
    const posts = stableSortDescByDate(readPosts());
    const published = posts.filter((p) => !p.draft);

    const bySlug = Object.fromEntries(published.map((p) => [p.slug, p]));

    const list = published.map((p) => {
        const { content: _content, ...rest } = p;
        return rest;
    });

    const ts = `// This file is auto-generated by scripts/generate-blog.mjs
// Do not edit manually.

import type { Post, PostListItem } from "@/lib/blog/types";

export const postsBySlug: Record<string, Post> = ${toTsString(bySlug)} as unknown as Record<string, Post>;
export const postList: PostListItem[] = ${toTsString(list)} as unknown as PostListItem[];
`;

    fs.mkdirSync(path.dirname(outFile), { recursive: true });
    fs.writeFileSync(outFile, ts, "utf8");
}

generate();
