import { SITE_NAME, SITE_URL, absoluteUrl } from "@/lib/site";

type JsonLd = Record<string, unknown>;

export function organizationJsonLd(): JsonLd {
    return {
        "@context": "https://schema.org",
        "@type": "Organization",
        name: SITE_NAME,
        url: SITE_URL,
        // Logo can be generated by Next's /icon route.
        logo: absoluteUrl("/icon"),
    };
}

export function websiteJsonLd(): JsonLd {
    return {
        "@context": "https://schema.org",
        "@type": "WebSite",
        name: SITE_NAME,
        url: SITE_URL,
        inLanguage: "zh-CN",
    };
}

export function blogPostingJsonLd(params: {
    title: string;
    description?: string;
    slug: string;
    datePublished: string;
    dateModified?: string;
}): JsonLd {
    return {
        "@context": "https://schema.org",
        "@type": "BlogPosting",
        headline: params.title,
        description: params.description,
        datePublished: params.datePublished,
        dateModified: params.dateModified ?? params.datePublished,
        inLanguage: "zh-CN",
        mainEntityOfPage: {
            "@type": "WebPage",
            "@id": absoluteUrl(`/blog/${params.slug}`),
        },
        author: {
            "@type": "Organization",
            name: SITE_NAME,
        },
        publisher: {
            "@type": "Organization",
            name: SITE_NAME,
        },
    };
}

export function mobileApplicationJsonLd(): JsonLd {
    return {
        "@context": "https://schema.org",
        "@type": "MobileApplication",
        name: SITE_NAME,
        operatingSystem: "ANDROID",
        applicationCategory: "BusinessApplication",
        offers: {
            "@type": "Offer",
            price: "0",
            priceCurrency: "CNY",
        },
        downloadUrl: absoluteUrl("/download"),
        url: SITE_URL,
    };
}

export function JsonLdScript({ data }: { data: JsonLd }) {
    return (
        <script
            type="application/ld+json"
            // JSON-LD must be injected as raw JSON.
            dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
        />
    );
}
