// This file is auto-generated by scripts/generate-blog.mjs
// Do not edit manually.

import type { Post, PostListItem } from "@/lib/blog/types";

export const postsBySlug: Record<string, Post> = {} as unknown as Record<string, Post>;
export const postList: PostListItem[] = [] as unknown as PostListItem[];
