import { DarkTheme, DefaultTheme } from "@react-navigation/native";

export const THEME = {
    light: {
        background: "hsl(0 0% 95.6860%)", // #f4f4f4
        foreground: "hsl(36 8.1970% 11.9610%)", // #211f1c
        card: "hsl(0 0% 100%)",
        cardForeground: "hsl(36 8.1970% 11.9610%)",
        popover: "hsl(0 0% 100%)",
        popoverForeground: "hsl(36 8.1970% 11.9610%)",
        primary: "hsl(33.2730 93.2200% 53.7250%)", // #f7951b
        primaryForeground: "hsl(0 0% 100%)", // #211f1c
        secondary: "hsl(33 55% 92%)",
        secondaryForeground: "hsl(36.1540 100% 30.5880%)", // #9c5e00
        muted: "hsl(0 0% 95.6860%)",
        mutedForeground: "hsl(0 0% 60%)", // #999999
        accent: "hsl(33 80% 88%)",
        accentForeground: "hsl(36 8.1970% 11.9610%)",
        destructive: "hsl(353.5340 100% 45.4900%)", // #e80019
        destructiveForeground: "hsl(0 0% 98%)",
        border: "hsl(210 22.2222% 96.4706%)", // #f4f6f8
        input: "hsl(210 22.2222% 96.4706%)",
        ring: "hsl(33.2730 93.2200% 53.7250%)",
        radius: "0.75rem",
        chart1: "hsl(33.2730 93.2200% 53.7250%)",
        chart2: "hsl(190 60% 45%)",
        chart3: "hsl(220 70% 60%)",
        chart4: "hsl(340 55% 65%)",
        chart5: "hsl(120 45% 45%)",
        sidebar: "hsl(33 35% 95%)",
        sidebarForeground: "hsl(36 8.1970% 11.9610%)",
        sidebarPrimary: "hsl(33.2730 93.2200% 53.7250%)",
        sidebarPrimaryForeground: "hsl(36 8.1970% 11.9610%)",
        sidebarAccent: "hsl(33 70% 90%)",
        sidebarAccentForeground: "hsl(36 8.1970% 11.9610%)",
        sidebarBorder: "hsl(210 22.2222% 96.4706%)",
        sidebarRing: "hsl(33.2730 93.2200% 53.7250%)",
        fontSans: "AR One Sans, ui-sans-serif, sans-serif, system-ui",
        fontSerif: '"Lora", serif',
        fontMono: '"JetBrains Mono", monospace',
        shadowX: "0rem",
        shadowY: "0.0625rem",
        shadowBlur: "0.75rem",
        shadowSpread: "0rem",
        shadowOpacity: "0.1",
        shadowColor: "hsl(0 0% 0%)",
        shadow2xs: "0rem 0.0625rem 0.75rem 0rem hsl(0 0% 0% / 0.1)",
        shadowXs: "0rem 0.0625rem 0.75rem 0rem hsl(0 0% 0% / 0.1)",
        shadowSm: "0rem 0.0625rem 0.75rem 0rem hsl(0 0% 0% / 0.1)",
        shadow: "0rem 0.0625rem 0.75rem 0rem hsl(0 0% 0% / 0.1)",
        shadowMd: "0rem 0.125rem 0.75rem 0rem hsl(0 0% 0% / 0.12)",
        shadowLg: "0rem 0.25rem 1rem 0rem hsl(0 0% 0% / 0.14)",
        shadowXl: "0rem 0.5rem 1.5rem 0rem hsl(0 0% 0% / 0.16)",
        shadow2xl: "0rem 0.75rem 2rem 0rem hsl(0 0% 0% / 0.2)",
        trackingNormal: "0em",
        spacing: "0.25rem",
    },
    dark: {
        background: "hsl(0 0% 7.0590%)", // #121212
        foreground: "hsl(0 0% 96.0780%)", // #f5f5f5
        card: "hsl(0 0% 10.1960%)", // #1a1a1a
        cardForeground: "hsl(0 0% 96.0780%)",
        popover: "hsl(0 0% 10.1960%)",
        popoverForeground: "hsl(0 0% 96.0780%)",
        primary: "hsl(33.2730 93.2200% 53.7250%)", // #f7951b
        primaryForeground: "hsl(0 0% 100%)", // #211f1c
        secondary: "hsl(0 0% 16.8630%)", // #2b2b2b
        secondaryForeground: "hsl(0 0% 96.0780%)",
        muted: "hsl(0 0% 12.1570%)", // #1f1f1f
        mutedForeground: "hsl(0 0% 63.9220%)", // #a3a3a3
        accent: "hsl(0 0% 16.8630%)",
        accentForeground: "hsl(0 0% 96.0780%)",
        destructive: "hsl(353.5340 100% 45.4900%)", // #e80019
        destructiveForeground: "hsl(0 0% 98%)",
        border: "hsl(0 0% 16.4710%)", // #2a2a2a
        input: "hsl(0 0% 16.4710%)",
        ring: "hsl(33.2730 93.2200% 53.7250%)",
        radius: "0.75rem",
        chart1: "hsl(33.2730 93.2200% 53.7250%)",
        chart2: "hsl(190 60% 45%)",
        chart3: "hsl(220 70% 60%)",
        chart4: "hsl(340 55% 65%)",
        chart5: "hsl(120 45% 45%)",
        sidebar: "hsl(0 0% 5.8820%)", // #0f0f0f
        sidebarForeground: "hsl(0 0% 96.0780%)",
        sidebarPrimary: "hsl(33.2730 93.2200% 53.7250%)",
        sidebarPrimaryForeground: "hsl(36 8.1970% 11.9610%)",
        sidebarAccent: "hsl(0 0% 16.8630%)",
        sidebarAccentForeground: "hsl(0 0% 96.0780%)",
        sidebarBorder: "hsl(0 0% 16.4710%)",
        sidebarRing: "hsl(33.2730 93.2200% 53.7250%)",
        fontSans: "AR One Sans, ui-sans-serif, sans-serif, system-ui",
        fontSerif: '"Lora", serif',
        fontMono: '"JetBrains Mono", monospace',
        shadowX: "0rem",
        shadowY: "0.3rem",
        shadowBlur: "0.6rem",
        shadowSpread: "-0.2rem",
        shadowOpacity: "0.2",
        shadowColor: "hsl(0, 0%, 0%)",
        shadow2xs: "0rem 0.3rem 0.6rem -0.2rem hsl(0 0% 0% / 0.1)",
        shadowXs: "0rem 0.3rem 0.6rem -0.2rem hsl(0 0% 0% / 0.1)",
        shadowSm:
            "0rem 0.3rem 0.6rem -0.2rem hsl(0 0% 0% / 0.2), 0rem 1px 2px -1.2px hsl(0 0% 0% / 0.2)",
        shadow: "0rem 0.3rem 0.6rem -0.2rem hsl(0 0% 0% / 0.2), 0rem 1px 2px -1.2px hsl(0 0% 0% / 0.2)",
        shadowMd:
            "0rem 0.3rem 0.6rem -0.2rem hsl(0 0% 0% / 0.2), 0rem 2px 4px -1.2px hsl(0 0% 0% / 0.2)",
        shadowLg:
            "0rem 0.3rem 0.6rem -0.2rem hsl(0 0% 0% / 0.2), 0rem 4px 6px -1.2px hsl(0 0% 0% / 0.2)",
        shadowXl:
            "0rem 0.3rem 0.6rem -0.2rem hsl(0 0% 0% / 0.2), 0rem 8px 10px -1.2px hsl(0 0% 0% / 0.2)",
        shadow2xl: "0rem 0.3rem 0.6rem -0.2rem hsl(0 0% 0% / 0.5)",
        trackingNormal: "0em",
        spacing: "0.25rem",
    },
};

export const NAV_THEME = {
    light: {
        ...DefaultTheme,
        colors: {
            notification: THEME.light.destructive,
            text: THEME.light.foreground,
            background: THEME.light.background,
            foreground: THEME.light.foreground,
            card: THEME.light.card,
            cardForeground: THEME.light.cardForeground,
            popover: THEME.light.popover,
            popoverForeground: THEME.light.popoverForeground,
            primary: THEME.light.primary,
            primaryForeground: THEME.light.primaryForeground,
            secondary: THEME.light.secondary,
            secondaryForeground: THEME.light.secondaryForeground,
            muted: THEME.light.muted,
            mutedForeground: THEME.light.mutedForeground,
            accent: THEME.light.accent,
            accentForeground: THEME.light.accentForeground,
            destructive: THEME.light.destructive,
            destructiveForeground: THEME.light.destructiveForeground,
            border: THEME.light.border,
            input: THEME.light.input,
            ring: THEME.light.ring,
            radius: THEME.light.radius,
            chart1: THEME.light.chart1,
            chart2: THEME.light.chart2,
            chart3: THEME.light.chart3,
            chart4: THEME.light.chart4,
            chart5: THEME.light.chart5,
            sidebar: THEME.light.sidebar,
            sidebarForeground: THEME.light.sidebarForeground,
            sidebarPrimary: THEME.light.sidebarPrimary,
            sidebarPrimaryForeground: THEME.light.sidebarPrimaryForeground,
            sidebarAccent: THEME.light.sidebarAccent,
            sidebarAccentForeground: THEME.light.sidebarAccentForeground,
            sidebarBorder: THEME.light.sidebarBorder,
            sidebarRing: THEME.light.sidebarRing,
            fontSans: THEME.light.fontSans,
            fontSerif: THEME.light.fontSerif,
            fontMono: THEME.light.fontMono,
            shadowX: THEME.light.shadowX,
            shadowY: THEME.light.shadowY,
            shadowBlur: THEME.light.shadowBlur,
            shadowSpread: THEME.light.shadowSpread,
            shadowOpacity: THEME.light.shadowOpacity,
            shadowColor: THEME.light.shadowColor,
            shadow2xs: THEME.light.shadow2xs,
            shadowXs: THEME.light.shadowXs,
            shadowSm: THEME.light.shadowSm,
            shadow: THEME.light.shadow,
            shadowMd: THEME.light.shadowMd,
            shadowLg: THEME.light.shadowLg,
            shadowXl: THEME.light.shadowXl,
            shadow2xl: THEME.light.shadow2xl,
            trackingNormal: THEME.light.trackingNormal,
            spacing: THEME.light.spacing,
        },
    },
    dark: {
        ...DarkTheme,
        colors: {
            notification: THEME.dark.destructive,
            text: THEME.dark.foreground,
            background: THEME.dark.background,
            foreground: THEME.dark.foreground,
            card: THEME.dark.card,
            cardForeground: THEME.dark.cardForeground,
            popover: THEME.dark.popover,
            popoverForeground: THEME.dark.popoverForeground,
            primary: THEME.dark.primary,
            primaryForeground: THEME.dark.primaryForeground,
            secondary: THEME.dark.secondary,
            secondaryForeground: THEME.dark.secondaryForeground,
            muted: THEME.dark.muted,
            mutedForeground: THEME.dark.mutedForeground,
            accent: THEME.dark.accent,
            accentForeground: THEME.dark.accentForeground,
            destructive: THEME.dark.destructive,
            destructiveForeground: THEME.dark.destructiveForeground,
            border: THEME.dark.border,
            input: THEME.dark.input,
            ring: THEME.dark.ring,
            radius: THEME.dark.radius,
            chart1: THEME.dark.chart1,
            chart2: THEME.dark.chart2,
            chart3: THEME.dark.chart3,
            chart4: THEME.dark.chart4,
            chart5: THEME.dark.chart5,
            sidebar: THEME.dark.sidebar,
            sidebarForeground: THEME.dark.sidebarForeground,
            sidebarPrimary: THEME.dark.sidebarPrimary,
            sidebarPrimaryForeground: THEME.dark.sidebarPrimaryForeground,
            sidebarAccent: THEME.dark.sidebarAccent,
            sidebarAccentForeground: THEME.dark.sidebarAccentForeground,
            sidebarBorder: THEME.dark.sidebarBorder,
            sidebarRing: THEME.dark.sidebarRing,
            fontSans: THEME.dark.fontSans,
            fontSerif: THEME.dark.fontSerif,
            fontMono: THEME.dark.fontMono,
            shadowX: THEME.dark.shadowX,
            shadowY: THEME.dark.shadowY,
            shadowBlur: THEME.dark.shadowBlur,
            shadowSpread: THEME.dark.shadowSpread,
            shadowOpacity: THEME.dark.shadowOpacity,
            shadowColor: THEME.dark.shadowColor,
            shadow2xs: THEME.dark.shadow2xs,
            shadowXs: THEME.dark.shadowXs,
            shadowSm: THEME.dark.shadowSm,
            shadow: THEME.dark.shadow,
            shadowMd: THEME.dark.shadowMd,
            shadowLg: THEME.dark.shadowLg,
            shadowXl: THEME.dark.shadowXl,
            shadow2xl: THEME.dark.shadow2xl,
            trackingNormal: THEME.dark.trackingNormal,
            spacing: THEME.dark.spacing,
        },
    },
};
